# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
    level:
        ROOT: DEBUG
        io.github.jhipster: DEBUG
        io.github.iconizer: DEBUG

spring:
    profiles:
        active: dev
        include: swagger
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use Webpack dev server + BrowserSync for livereload
    jackson:
        serialization.indent_output: true

    datasource:
            type: com.zaxxer.hikari.HikariDataSource
            url: jdbc:mysql://localhost:3306/iconizer?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
            username: root
            password: Iconizer@1
            hikari:
                data-source-properties:
                    cachePrepStmts: true
                    prepStmtCacheSize: 250
                    prepStmtCacheSqlLimit: 2048
                    useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: false
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
#            hibernate.cache.region.factory_class: io.github.jhipster.config.jcache.NoDefaultJCacheRegionFactory
    liquibase:
        contexts: dev
    mail:
        host: localhost
        port: 1025
        username:
        password:
    messages:
        cache-duration: PT1S # 1 second, see the ISO 8601 standard
    thymeleaf:
        cache: false

# ===================================================================
# To enable SSL, generate a certificate using:
# keytool -genkey -alias iconizer -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# https://maximilian-boehm.com/hp2121/Create-a-Java-Keystore-JKS-from-Let-s-Encrypt-Certificates.htm
#
# Then, modify the server.ssl properties so your "server" configuration looks like:
#
# server:
#    port: 8443
#    ssl:
#        key-store: keystore.p12
#        key-store-password: <your-password>
#        key-store-type: PKCS12
#        key-alias: iconizer
# ===================================================================
server:
    port: 8080

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
    http:
        version: V_1_1 # To use HTTP/2 you will need SSL support (see above the "server.ssl" configuration)
    cache: # Cache configuration
        ehcache: # Ehcache configuration
            time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
            max-entries: 100 # Number of objects in each cache entry
    # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
    cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Authorization,Link,X-Total-Count"
        allow-credentials: true
        max-age: 1800
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
                # Token is valid 24 hours
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
    mail: # specific JHipster mail property, for standard properties see MailProperties
        enabled: true
        from: admin@Iconizer.com
        base-url: http://127.0.0.1:8080
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx:
            enabled: true
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            report-frequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queue-size: 512

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
# ===================================================================

application:
    jhipster-cmd:
        cmd: C:\
        timeout: 60
    tmp-folder: C:\work\tmp
    #github:
    #    host: https://github.com
    #    client-id: a0550cf3a8837ccc7159
    #    client-secret: 4cb24eeeacc539437f94800d215c5bd5ee6c7c71
    #    jhipster-bot-oauth-token: d74e1a6c7f682d1feb0666ce17745597dd55b040 

#application:
#    tmp-folder: /tmp
#    jhipster-cmd:
#        cmd: XXX
#        timeout: 120
#    github:
#        host: https://github.com
#        client-id: XXX
#        client-secret: XXX
#        jhipster-bot-oauth-token: XXX
#    gitlab:
#        host: https://gitlab.com
#        client-id: XXX
#        client-secret: XXX
#        redirect-uri: XXX
#        jhipster-bot-oauth-token: XXX



mortgage1:
    app:
        gateway:
            key: GatewayName
            value: gatewayapp
        product:
            key: MSApp1
            value: productapp
        service:
            key: MSApp2
            value: serviceapp
        template: mortgagebank1.vm
        type: Microservices
mortgage2:
    app:
        gateway:
            key: GatewayName
            value: productapp
        product:
            key: MSApp1
            value: gatewayapp
        service:
            key: MSApp2
            value: serviceapp
        template: mortgagebank2.vm
        type: Microservices
ticketmanagement:
    app:
        keys: ProjectName
        template: ticketmanagement.vmp
        type: Monolith
        values: BugTrackerApp

